version: '3.10'

services:
  mongodb:
    image: mongo:5.0.8
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: always

  api:
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
    restart: always
    depends_on:
      - mongodb
    volumes:
      - .:/app